### ISSUE TITLE
GitHub source out of date

### ISSUE THREAD

**Issue by Herohtar** [ehrt74/dart_lang_fft#1]
According to the code here this is only v0.0.9, but the package on Pub is 0.0.13. Is the project being maintained somewhere else?

**Comment by ehrt74** [comment]
Hello!

Sorry, I hadn't updated the git repo. I've just pushed version 0.0.14.

**Comment by Herohtar** [comment]
Great! But it doesn't seem to be in a working state...
`The return type 'Queue' isn't a 'Iterable<Complex>', as defined by the method '_transform'.` on line 38 of fft.dart

**Comment by ehrt74** [comment]
sorry, i'd forgotten a type annotation. i have no idea how it worked on my system :) It may work now. however, my dart2 sdk appears to be broken. if it's still broken, i can take a look at it at about 19:00 GMT.

just pushed 0.0.15

**Comment by Herohtar** [comment]
It gets further, but still broken: `type 'SubListIterable<dynamic>' is not a subtype of type 'Iterable<Complex>'` on line 34 of fft.dart

But it also dies before that with a stack overflow due to the SplitList recursion if you have more than 8192 samples (16384, since it has to be a power of 2).

**Comment by ehrt74** [comment]
hello! my dart environment isn't showing the type errors, and it doesn't complain when i try to run it :(

I've replaced a lot of the Queues and Iterables with Lists and uploaded a new version. The problems with recursion causing stack overflows should now be fixed.

**Comment by Herohtar** [comment]
It seems to be functional now.
